### ISSUE TITLE
PCB design file available?

### ISSUE THREAD

**Issue by jeremyherbert** [orbcode/orbtrace_hw#2]
Hi,

It appears that there is a PDF schematic (from Altium?) in this repository, but no design files. Do you plan to share these?

**Comment by mubes** [comment]
Hi Jeremy,
We've made all the design files available but not the electronic manufacturing drawing package. If you need that then please contact us off-list and we can see if we can sort something out. The intention is to prevent someone coming along and making ORBTrace commercially having put no effort into it's gestation. It certainly isn't to prevent someone making a batch for their own use.

**Comment by 424778940z** [comment]
Sorry for reply to this old issue, is the project still active? 
There seems no one selling a complete probe, I would have to build it myself
May I know the process for obtain design files?
