### ISSUE TITLE
ORBTrace mini: Information on SLG46811 configuration

### ISSUE THREAD

**Issue by arbrauns** [orbcode/orbtrace_hw#3]
Hi! The ORBTrace mini contains a pre-programmed SLG46811 that does _something_ to the data stream going to the SK6805 LEDs. I'm assuming it measures the supply voltages and injects corresponsing colour information into the LED stream, but I'm not sure how exactly it does that - is the .gpx file for the chip configuration available somewhere? Thanks!

**Comment by zyp** [comment]
Hi, I've just published the configurations for both greenpaks, you can find them here:

https://github.com/orbcode/orbtrace_hw/tree/main/hw/orbtrace_mini/greenpak
